### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by deven10100** [R1KO/Throwing-Knives#1]
Hello i've tried recompiling and using your version of smx, no luck, no error logs just does not work. But plugin loads fine. Just no knives get thrown.

**Comment by R1KO** [comment]
last version?

**Comment by deven10100** [comment]
1.3 

& latest version of sourcemod

**Comment by deven10100** [comment]
![csgo_2018-01-14_19-39-22](https://user-images.githubusercontent.com/13183198/34922817-df5dc9ea-f962-11e7-9520-d522f85fb033.jpg)
 but no knives shoot

**Comment by R1KO** [comment]
@deven10100 check this http://joxi.ru/KAgJJbPigynlO2

**Comment by deven10100** [comment]
@R1KO 

Just tried above version, Still no knives get thrown i even removed !ws & !knife / restarted server to see if maybe its got conflicts, Still same nothing gets thrown.
